# Data validation and pre-processing technique

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
#import library packages
import pandas as p
import numpy as n

In [3]:
#Load given dataset
data = p.read_csv("Bitcoin.csv")

Before drop the given dataset

In [4]:
data.head()

,Date,BTC price [USD],n-transactions,fee [USD],btc search trends,Gold price[USD],SP500 close index,Oil WTI price[USD],M2(Not seasonally adjusted)[1e+09 USD]
0,2014-01-02,749.27,54770.0,0.18,8,1225.0,1831.98,95.14,11089.3
1,2014-01-03,781.23,60980.0,NaN,8,1238.4,1831.37,93.66,11089.3
2,2014-01-04,807.39,52052.0,NaN,8,NaN,NaN,NaN,11089.3
3,2014-01-05,828.74,58662.0,0.38,8,NaN,NaN,NaN,11089.3
4,2014-01-06,904.98,67358.0,NaN,8,1237.8,1826.77,93.12,11089.3

In [5]:
data.shape

(2310, 9)

After drop the given dataset

In [6]:
df=data.dropna()
df.head()

,Date,BTC price [USD],n-transactions,fee [USD],btc search trends,Gold price[USD],SP500 close index,Oil WTI price[USD],M2(Not seasonally adjusted)[1e+09 USD]
0,2014-01-02,749.27,54770.0,0.18,8,1225.0,1831.98,95.14,11089.3
6,2014-01-08,790.00,61439.0,0.18,8,1225.3,1837.49,91.90,11089.3
12,2014-01-14,823.00,57378.0,0.22,8,1245.2,1838.88,92.15,11089.3
15,2014-01-17,817.15,59026.0,0.19,8,1251.7,1838.70,93.96,11089.3
21,2014-01-23,819.62,63576.0,0.19,8,1262.6,1828.46,97.23,11089.3

In [7]:
df.shape

(1002, 9)

In [8]:
#show columns
df.columns

Index(['Date', 'BTC price [USD]', 'n-transactions', 'fee [USD]',
       'btc search trends', 'Gold price[USD]', 'SP500 close index',
       'Oil WTI price[USD]', 'M2(Not seasonally adjusted)[1e+09 USD]'],
      dtype='object')

In [9]:
df.rename(columns={"BTC price [USD]":"BTC_price_USD"},inplace=True)
df.rename(columns={"n-transactions":"n_transactions"},inplace=True)
df.rename(columns={"fee [USD]":"fee_USD"},inplace=True)
df.rename(columns={"btc search trends":"btc_search_trends"},inplace=True)
df.rename(columns={"Gold price[USD]":"Gold_price_USD"},inplace=True)
df.rename(columns={"SP500 close index":"SP500_close_index"},inplace=True)
df.rename(columns={"Oil WTI price[USD]":"Oil_WTI_price_USD"},inplace=True)
df.rename(columns={"M2(Not seasonally adjusted)[1e+09 USD]":"M2_money_supply_USA"},inplace=True)

In [10]:
df.columns

Index(['Date', 'BTC_price_USD', 'n_transactions', 'fee_USD',
       'btc_search_trends', 'Gold_price_USD', 'SP500_close_index',
       'Oil_WTI_price_USD', 'M2_money_supply_USA'],
      dtype='object')

In [11]:
df['n_transactions'].unique()

array([ 54770.,  61439.,  57378., ..., 311217., 323475., 331401.])

In [12]:
df['fee_USD'].unique()

array([1.800e-01, 2.200e-01, 1.900e-01, 1.700e-01, 1.600e-01, 1.400e-01,
       1.300e-01, 1.100e-01, 1.500e-01, 1.200e-01, 9.000e-02, 1.000e-01,
       8.000e-02, 7.000e-02, 6.000e-02, 5.000e-02, 4.000e-02, 3.000e-02,
       2.100e-01, 2.000e-01, 2.700e-01, 2.300e-01, 3.000e-01, 2.500e-01,
       2.800e-01, 2.900e-01, 3.100e-01, 3.300e-01, 4.200e-01, 3.600e-01,
       4.300e-01, 5.000e-01, 5.500e-01, 4.500e-01, 6.100e-01, 7.200e-01,
       6.800e-01, 8.300e-01, 9.800e-01, 9.200e-01, 1.000e+00, 8.500e-01,
       9.400e-01, 7.900e-01, 8.400e-01, 7.300e-01, 9.000e-01, 8.800e-01,
       1.040e+00, 1.180e+00, 1.540e+00, 1.410e+00, 1.740e+00, 2.740e+00,
       2.800e+00, 3.370e+00, 4.270e+00, 5.560e+00, 4.460e+00, 3.380e+00,
       3.660e+00, 3.830e+00, 4.500e+00, 3.540e+00, 3.520e+00, 3.390e+00,
       3.470e+00, 3.730e+00, 3.360e+00, 2.450e+00, 2.790e+00, 2.510e+00,
       2.000e+00, 1.830e+00, 2.030e+00, 2.020e+00, 2.140e+00, 1.770e+00,
       1.940e+00, 2.530e+00, 1.900e+00, 1.800e+00, 1.760e+00, 1.850e+00,
       2.090e+00, 2.320e+00, 1.600e+00, 1.690e+00, 1.360e+00, 1.620e+00,
       1.970e+00, 2.540e+00, 2.910e+00, 4.100e+00, 4.720e+00, 5.270e+00,
       4.570e+00, 4.560e+00, 5.070e+00, 6.720e+00, 7.140e+00, 7.880e+00,
       8.930e+00, 7.280e+00, 7.370e+00, 6.510e+00, 6.900e+00, 6.480e+00,
       4.380e+00, 4.480e+00, 4.600e+00, 3.490e+00, 2.660e+00, 2.470e+00,
       1.990e+00, 2.050e+00, 2.040e+00, 3.060e+00, 2.430e+00, 1.860e+00,
       2.490e+00, 2.220e+00, 2.250e+00, 1.880e+00, 2.690e+00, 2.330e+00,
       2.300e+00, 2.670e+00, 3.070e+00, 5.150e+00, 3.150e+00, 3.020e+00,
       3.030e+00, 3.450e+00, 3.300e+00, 2.460e+00, 3.920e+00, 5.230e+00,
       5.480e+00, 5.670e+00, 7.100e+00, 6.670e+00, 6.210e+00, 6.430e+00,
       7.670e+00, 8.190e+00, 1.077e+01, 1.477e+01, 1.327e+01, 1.212e+01,
       1.024e+01, 8.270e+00, 6.810e+00, 6.700e+00, 6.190e+00, 4.910e+00,
       6.620e+00, 7.650e+00, 7.000e+00, 6.110e+00, 6.390e+00, 6.340e+00,
       7.270e+00, 1.498e+01, 2.651e+01, 2.137e+01, 2.454e+01, 2.397e+01,
       2.177e+01, 2.581e+01, 2.700e+01, 3.200e+01, 4.164e+01, 5.479e+01,
       5.464e+01, 5.140e+01, 3.994e+01, 3.681e+01, 3.228e+01, 3.001e+01,
       2.828e+01, 2.718e+01, 3.227e+01, 3.225e+01, 3.100e+01, 2.942e+01,
       2.824e+01, 2.814e+01, 2.833e+01, 2.277e+01, 2.441e+01, 2.309e+01,
       2.224e+01, 1.126e+01, 1.241e+01, 1.052e+01, 1.042e+01, 9.770e+00,
       7.160e+00, 7.920e+00, 7.860e+00, 9.950e+00, 4.580e+00, 4.160e+00,
       4.110e+00, 4.190e+00, 3.230e+00, 2.930e+00, 3.170e+00, 3.110e+00,
       2.980e+00, 2.150e+00, 2.100e+00, 3.960e+00, 6.240e+00, 2.890e+00,
       2.370e+00, 1.560e+00, 2.390e+00, 2.860e+00, 1.700e+00, 1.440e+00,
       1.320e+00, 1.120e+00, 1.390e+00, 1.430e+00, 1.310e+00, 1.240e+00,
       1.230e+00, 1.170e+00, 1.070e+00, 1.050e+00, 8.900e-01, 9.300e-01,
       9.100e-01, 8.700e-01, 1.250e+00, 1.340e+00, 1.060e+00, 1.020e+00,
       1.150e+00, 2.760e+00, 1.590e+00, 1.420e+00, 1.670e+00, 1.750e+00,
       1.630e+00, 1.460e+00, 1.190e+00, 1.570e+00, 1.520e+00, 1.280e+00,
       2.350e+00, 1.080e+00, 1.160e+00, 8.200e-01, 7.800e-01, 7.400e-01,
       7.500e-01, 6.500e-01, 7.700e-01, 1.110e+00, 8.600e-01, 5.800e-01,
       2.940e+00, 6.740e+00, 2.500e+00, 1.030e+00, 7.600e-01, 7.000e-01,
       6.400e-01, 5.700e-01, 5.900e-01, 9.900e-01, 9.500e-01, 6.700e-01,
       5.600e-01, 6.000e-01, 6.600e-01, 6.900e-01, 8.000e-01, 6.200e-01,
       4.600e-01, 4.900e-01, 4.100e-01, 6.300e-01, 5.100e-01, 5.300e-01,
       4.400e-01, 4.700e-01, 4.800e-01, 3.900e-01, 3.500e-01, 1.090e+00,
       5.200e-01, 3.800e-01, 2.600e-01, 2.400e-01, 3.200e-01, 4.000e-01,
       3.400e-01, 1.330e+00, 2.170e+00, 1.470e+00, 1.820e+00, 1.730e+00,
       1.480e+00, 1.350e+00, 1.140e+00, 1.710e+00, 1.790e+00, 1.270e+00,
       1.650e+00, 1.780e+00, 2.400e+00, 2.880e+00, 4.200e+00, 4.860e+00,
       3.850e+00, 4.230e+00, 3.550e+00, 3.240e+00, 4.340e+00, 3.990e+00,
       4.320e+00, 5.730e+00, 5.760e+00, 4.550e+00, 3.320e+00, 2.600e+00,
       2.560e+00, 2.710e+00, 2.410e+00, 3.790e+00, 5.910e+00, 6.530e+00,
       5.240e+00, 4.030e+00, 3.250e+00, 2.110e+00, 2.440e+00, 3.440e+00,
       2.840e+00, 2.480e+00, 1.610e+00, 1.640e+00, 1.660e+00, 1.130e+00,
       1.400e+00, 2.240e+00, 1.950e+00, 2.230e+00, 1.680e+00, 1.100e+00,
       1.210e+00, 9.600e-01, 1.200e+00, 7.100e-01, 3.700e-01, 5.400e-01,
       1.010e+00, 8.100e-01, 1.380e+00, 1.300e+00])

In [13]:
df["btc_search_trends"].unique()

array([  8,   9,   6,   4,   3,   2,   5,   7,  15,  14,  12,  20,  21,
        22,  44, 100,  54,  40,  18,  13,  10,  17,  11,  19,  16],
      dtype=int64)

In [14]:
df["Gold_price_USD"].unique()

array([1225. , 1225.3, 1245.2, 1251.7, 1262.6, 1262.2, 1263.3, 1274.8,
       1300.4, 1320.6, 1343. , 1321.4, 1350.1, 1351.7, 1370.3, 1359. ,
       1336. , 1311.2, 1294.7, 1283.4, 1284.4, 1305.5, 1300. , 1288. ,
       1290.5, 1295.6, 1308.3, 1287.3, 1293.5, 1265.4, 1245.6, 1243.7,
       1253. , 1260.8, 1271.7, 1316.2, 1318. , 1316.1, 1484.8, 1471.4,
       1492.9, 1460.7, 1472.1, 1460.3, 1456.7, 1451.1, 1441.9, 1467.3,
       1467.9, 1449. , 1434.1, 1433.1, 1443.8, 1425.5, 1404.6, 1387.8,
       1391.3, 1383.4, 1374.9, 1366.7, 1346.9, 1360.7, 1358.8, 1361.3,
       1371.8, 1355. , 1349.2, 1290.3, 1291. , 1281.3, 1281.4, 1313.4,
       1315.2, 1291.2, 1332.5, 1324.2, 1345.5, 1302. , 1305.6, 1289.7,
       1295.4, 1322.2, 1317.4, 1333.2, 1352.8, 1378.4, 1379.7, 1349.6,
       1347.4, 1336.9, 1301.2, 1291.9, 1285.2, 1280.7, 1288.1, 1282.6,
       1240.1, 1230.9, 1231.3, 1241.5, 1269.3, 1276.2, 1280.4, 1275.3,
       1269.8, 1265. , 1256.7, 1248.1, 1261. , 1260.5, 1294.2, 1281.7,
       1264.5, 1263.9, 1284.8, 1255. , 1254.8, 1254.6, 1239.1, 1230.3,
       1183.5, 1164. , 1174.6, 1167.4, 1161.1, 1181.7, 1186.3, 1191.9,
       1226.2, 1193. , 1205.3, 1184.5, 1171.9, 1180.3, 1183.7, 1202.9,
       1188.5, 1166.2, 1198.1, 1215.8, 1230.7, 1220.4, 1212.3, 1207.8,
       1184.8, 1180. , 1149.7, 1135. , 1116.5, 1123.4, 1114.3, 1102. ,
       1123.6, 1111. , 1097.7, 1117.8, 1118.2, 1125.3, 1152.5, 1127.5,
       1125.9, 1132.7, 1142.5, 1153.8, 1174.8, 1228.4, 1262.7, 1254. ,
       1268.6, 1307.1, 1301.8, 1311.6, 1272.4, 1277.8, 1260.4, 1256.2,
       1273.8, 1285.4, 1292.3, 1270.3, 1280.6, 1308.1, 1315.6, 1304.6,
       1312.8, 1315.1, 1299.2, 1270.7, 1287.9, 1292.7, 1317.7, 1329.2,
       1318.1, 1372.3, 1368.5, 1416.3, 1385. , 1377.8, 1384.8, 1384.1,
       1421.5, 1400. , 1397.4, 1406.1, 1402.7, 1399.9, 1375.3, 1376.5,
       1364.9, 1399.4, 1373.1, 1359.4, 1392.1, 1370.4, 1315.8, 1298.2,
       1307.6, 1306. , 1319. , 1323.9, 1360.6, 1328.8, 1278.7, 1275.6,
       1248.7, 1247.3, 1234.2, 1233.5, 1236.2, 1228.1, 1205.2, 1205. ,
       1229.4, 1235.3, 1269.5, 1273.7, 1280. , 1290.4, 1301.5, 1303.6,
       1302.4, 1307.4, 1326.6, 1327.3, 1302.1, 1280.1, 1274.5, 1305.4,
       1316.7, 1325.6, 1314.9, 1315.4, 1341.3, 1357.7, 1330.9, 1324. ,
       1293.7, 1294. , 1290.8, 1324.1, 1320. , 1332.7, 1331.1, 1353.5,
       1329.1, 1316.6, 1306.9, 1303.3, 1305.3, 1308.7, 1316. , 1306.7,
       1309.1, 1302.3, 1282.2, 1285. , 1274.3, 1276. , 1279.5, 1276.8,
       1287.1, 1314.2, 1313.7, 1311.5, 1310.1, 1330.3, 1328.4, 1334.1,
       1333.3, 1329.4, 1319.5, 1319.8, 1318.2, 1334.8, 1345.6, 1345.9,
       1335.3, 1338.6, 1347.8, 1346.7, 1352. , 1346.5, 1349.7, 1370.6,
       1373.7, 1368.9, 1385.1, 1399.2, 1393.9, 1406. , 1407.3, 1389.8,
       1384.7, 1387.2, 1383.1, 1368.3, 1376. , 1354.4, 1357.1, 1371.2,
       1361.8, 1348.4, 1349. , 1345.3, 1337.1, 1335.8, 1338. , 1337. ,
       1356.4, 1351.5, 1359.3, 1367.4, 1349.5, 1346.3, 1352.9, 1343.2,
       1343.9, 1341.2, 1342.5, 1333.1, 1335.1, 1340.9, 1333.7, 1340.6,
       1341.4, 1332.9, 1345.7, 1339.9, 1348.3, 1340.5, 1346.4, 1350.2,
       1344.7, 1345.4, 1364. , 1343.6, 1350.8, 1361.4, 1356.6, 1363.7,
       1351.4, 1342.3, 1330.1, 1331.2, 1313.1, 1311.8, 1322.4, 1330.6,
       1329.8, 1335.4, 1336.3, 1344.8, 1357.3, 1364.4, 1376.9, 1389. ,
       1392.3, 1393.3, 1391.8, 1385.2, 1392.2, 1395.3, 1409.6, 1412. ,
       1414.9, 1402.9, 1409.8, 1410.8, 1415.4, 1437.1, 1443.9, 1434.5,
       1422.1, 1417. , 1420.2, 1425.2, 1414.7, 1413. , 1405.5, 1390.8,
       1394.9, 1401.6, 1433.6, 1432.2, 1433.5, 1408.8, 1411. , 1411.8,
       1409.4, 1413.5, 1399.5, 1386.3, 1404.5, 1400.8, 1416.2, 1408.2,
       1403.3, 1407. , 1403.8, 1410.4, 1408.7, 1400.7, 1395.2, 1405.6,
       1411.2, 1434. , 1440. , 1426.8, 1407.9, 1405. , 1424.8, 1415.5,
       1418.7, 1407.1, 1418.6, 1424.5, 1439. , 1420.4, 1426.9, 1429.6,
       1428.3, 1432.5, 1427.8, 1417.2, 1403. , 1412.1, 1401.9, 1397. ,
       1402.6, 1398.1, 1385.4, 1384.3, 1391.4, 1393.7, 1393.2, 1392.8,
       1392. , 1401.1, 1396.9, 1368.8, 1370.8, 1368.6, 1369.9, 1369.7,
       1370.7, 1368.1, 1382.1, 1373.9, 1375.2, 1370.2, 1369.1, 1374.1,
       1373.5, 1374.4, 1375.5, 1380.6, 1349.3, 1351.1, 1341. , 1339.2,
       1329.6, 1325.7, 1320.2, 1309.9, 1327.6, 1324.8, 1329. , 1325.1,
       1313.3, 1309.5, 1308. , 1295.1, 1295.5, 1290.9, 1297.3, 1291.3,
       1297.2, 1291.6, 1289.1, 1287.8, 1289.9, 1284.1, 1276.3, 1276.9,
       1275.9, 1274.7, 1254.2, 1256. , 1239.8, 1238.8, 1238.9, 1248.6,
       1253.9, 1257.2, 1247. , 1266.8, 1268.2, 1265.1, 1257.9, 1259.5,
       1252. , 1254.4, 1257.5, 1253.4, 1259.6, 1256.9, 1265.6, 1255.5,
       1258.6, 1259.4, 1241. , 1249.9, 1261.3, 1257.3, 1256.1, 1243.5,
       1246.4, 1248. , 1276.6, 1285.6, 1286. , 1282.1, 1285.3, 1284. ,
       1292.2, 1286.2, 1287.4, 1290.7, 1279.9, 1269.2, 1293.2, 1288.3,
       1283.8, 1280.3, 1255.8, 1264.4, 1269.9, 1277.2, 1279.8, 1275.7,
       1282.9, 1277.9, 1278.5, 1279.1, 1288.5, 1295.7, 1292.6, 1301.9,
       1297.9, 1296. , 1298.9, 1296.3, 1290.1, 1300.5, 1301.6, 1304.4,
       1306.2, 1331.4, 1332.8, 1339. , 1334.9, 1341.1, 1336.8, 1337.5,
       1343.1, 1341.7, 1331.9, 1332.2, 1328.7, 1347.1, 1358.7, 1359.1,
       1367.9, 1365. , 1362.2, 1362.5, 1357.5, 1361.7, 1355.1, 1358.5,
       1365.1, 1375.7, 1372.2, 1363.8, 1358.6, 1341.6, 1326.8, 1328.2,
       1341.8, 1344.6, 1343.4, 1348.7, 1343.5, 1353.8, 1363.9, 1356.3,
       1351.3, 1329.9, 1333.5, 1329.5, 1330.7, 1337.4, 1349.4, 1328.9,
       1327.5, 1313.2, 1312.5, 1320.7, 1319.3, 1307.3, 1316.8, 1319.1,
       1320.9, 1316.5, 1322.3, 1335.5, 1319.6, 1309. , 1311. , 1318.6,
       1316.9, 1310.2, 1313.5, 1319.9, 1337.9, 1353.4, 1354.6, 1366.9,
       1354.8, 1356.9, 1362.3, 1369.6, 1367.7, 1420.3, 1423.4, 1441.4,
       1441.8, 1438.6, 1435.4, 1437.5, 1413.9, 1446.1, 1427.6, 1439.9,
       1434.6, 1440.2, 1441.5, 1439.3, 1451.6, 1456.4, 1454.7, 1455.2,
       1450. , 1452.1, 1443.1, 1448.1, 1449.2, 1457.7, 1453.7, 1448.4,
       1472.9, 1491. , 1498.6, 1533.6, 1524. , 1523.3, 1532. , 1529.3,
       1542.9, 1545.9, 1538.2, 1526.2, 1530.4, 1523.4, 1552.5, 1552.1,
       1567.2, 1564.5, 1552.6, 1545.5, 1571.9, 1576.2, 1541.3, 1531.5,
       1527.6, 1515.8, 1520. , 1524.5, 1517. , 1528.7, 1530.5, 1532.8,
       1523.2, 1548.5, 1557.1, 1528.9, 1489.8, 1505.6, 1524.6, 1530.1,
       1529.4, 1521.1, 1520.7, 1529.7, 1517.9, 1505.4, 1514.4, 1500.4,
       1510.8, 1515.1, 1510.4, 1504.6, 1503.9, 1512.2, 1521.3, 1522.2,
       1512.8, 1507.5, 1513.6, 1531.3, 1528.4, 1500.9, 1510.5, 1483.6,
       1480. , 1470.7, 1480.4, 1490.5, 1485.7, 1489.2, 1491.7, 1491.5,
       1481.1, 1481.2, 1474.7, 1477.8, 1471.1, 1483.2, 1479.4, 1494.8,
       1490.6, 1493.6, 1475.8, 1475.6, 1478.8, 1485.8, 1483.1, 1492.3,
       1491.6, 1491.9, 1489.9, 1495.5, 1492. , 1499.9, 1516. , 1525.7,
       1530.3, 1535.1, 1540.1, 1580.9, 1586.3, 1572.3, 1566.4, 1572.1,
       1562.7, 1556.5, 1565.6, 1562.2, 1569.9, 1568.7, 1577.3, 1583.9,
       1589.5, 1581.7, 1582. , 1595.1, 1593.8, 1588.3, 1561.4, 1575.8,
       1579.2, 1585.4, 1575.9, 1584.5, 1591.9, 1609.3, 1617.5, 1626.2,
       1654.6, 1682.4, 1655.8, 1648.9, 1648.2, 1571.8, 1599.5, 1647.2,
       1672. , 1676.1, 1678.6, 1663.3, 1645.4, 1593.2, 1519.5, 1488.6,
       1528.1, 1480.6, 1482.3, 1488.1, 1572.7, 1634.3, 1660.3, 1654.1,
       1643.2, 1596.6, 1591.4, 1637.7, 1645.7, 1693.9, 1683.7, 1684.3,
       1752.8, 1761.4, 1768.9, 1740.2, 1731.7, 1698.8, 1711.2, 1687.8,
       1738.3, 1745.4, 1735.6, 1723.8, 1722.2, 1713.4])

In [15]:
df["SP500_close_index"].unique()

array([1831.98, 1837.49, 1838.88, 1838.7 , 1828.46, 1774.2 , 1755.2 ,
       1797.02, 1799.84, 1829.83, 1828.75, 1845.12, 1859.45, 1845.73,
       1877.03, 1868.2 , 1872.25, 1866.52, 1857.44, 1849.04, 1872.34,
       1888.77, 1872.18, 1842.98, 1871.89, 1878.61, 1883.95, 1867.72,
       1878.48, 1896.65, 1870.85, 1888.03, 1911.91, 1923.57, 1924.97,
       1940.46, 1943.89, 1941.99, 1962.87, 1962.61, 1957.22, 1974.62,
       1963.71, 1967.57, 1977.1 , 1958.12, 1987.01, 1969.95, 1925.15,
       1938.99, 1909.57, 1946.72, 1981.6 , 1988.4 , 1997.92, 1996.74,
       2000.72, 1988.44, 1985.54, 1984.13, 2011.36, 1998.3 , 1972.29,
       1967.9 , 1964.82, 1928.21, 1862.49, 1941.28, 1964.58, 1982.3 ,
       2012.1 , 2031.92, 2038.26, 2039.33, 2048.72, 2067.03, 2067.56,
       2053.44, 2071.92, 2026.14, 1972.74, 2070.65, 2078.54, 2058.9 ,
       2002.61, 2044.81, 2028.26, 1992.67, 2032.12, 2029.55, 1994.99,
       2020.85, 2062.52, 2068.53, 2100.34, 2110.3 , 2109.66, 2110.74,
       2098.53, 2044.16, 2053.4 , 2081.19, 2089.27, 2061.05, 2059.69,
       2076.33, 2102.06, 2092.43, 2104.99, 2107.96, 2114.76, 2108.29,
       2114.49, 2088.  , 2098.48, 2127.83, 2126.06, 2120.79, 2114.07,
       2080.15, 2094.11, 2084.43, 2121.24, 2108.58, 2063.11, 2068.76,
       2051.31, 2107.4 , 2119.21, 2079.65, 2067.64, 2108.63, 2099.84,
       2084.07, 2091.54, 2102.44, 2035.73, 1940.51, 1913.85, 1921.22,
       1952.29, 1995.31, 1942.74, 1931.34, 1881.77, 1923.82, 1995.83,
       2003.69, 2033.11, 2033.66, 2052.51, 2065.89, 2079.36, 2104.05,
       2099.93, 2075.  , 2050.44, 2089.17, 2086.59, 2079.51, 2063.59,
       2012.37, 2021.94, 2041.89, 2064.29, 2078.36, 2012.66, 1943.09,
       1890.28, 1881.33, 1906.9 , 1877.08, 1893.36, 1912.53, 1852.21,
       1864.78, 1917.83, 1929.8 , 1978.35, 1999.99, 2001.76, 1989.57,
       2027.22, 2049.8 , 2055.01, 2072.78, 2066.13, 2041.91, 2082.42,
       2100.8 , 2091.58, 2087.79, 2075.81, 2051.12, 2084.39, 2046.61,
       2066.66, 2040.04, 2090.54, 2096.95, 2099.13, 2109.41, 2115.48,
       2071.5 , 2088.9 , 2037.41, 2000.54, 2098.86, 2099.73, 2152.14,
       2161.74, 2166.89, 2165.17, 2166.58, 2157.03, 2182.87, 2180.89,
       2185.79, 2182.22, 2186.9 , 2169.04, 2180.38, 2170.86, 2186.16,
       2127.02, 2139.16, 2139.12, 2177.18, 2171.37, 2150.49, 2153.74,
       2163.66, 2132.55, 2144.29, 2143.16, 2126.41, 2097.94, 2139.56,
       2164.45, 2164.2 , 2187.12, 2204.72, 2204.66, 2191.95, 2204.71,
       2246.19, 2253.28, 2270.76, 2263.79, 2249.26, 2270.75, 2268.9 ,
       2274.64, 2263.69, 2298.37, 2278.87, 2297.42, 2292.56, 2307.87,
       2349.25, 2365.38, 2367.34, 2369.75, 2381.92, 2362.98, 2365.45,
       2378.25, 2373.47, 2345.96, 2341.59, 2368.06, 2352.95, 2353.78,
       2349.01, 2355.84, 2387.45, 2391.17, 2399.29, 2399.38, 2394.44,
       2357.03, 2398.42, 2415.82, 2430.06, 2433.14, 2440.35, 2433.15,
       2453.46, 2437.03, 2435.61, 2434.5 , 2438.3 , 2439.07, 2419.38,
       2440.69, 2419.7 , 2423.41, 2432.54, 2409.75, 2425.18, 2427.43,
       2425.53, 2443.25, 2447.83, 2459.27, 2459.14, 2460.61, 2473.83,
       2473.45, 2472.54, 2469.91, 2477.13, 2477.83, 2475.42, 2472.1 ,
       2470.3 , 2476.35, 2477.57, 2472.16, 2476.83, 2480.91, 2474.92,
       2474.02, 2438.21, 2441.32, 2465.84, 2464.61, 2468.11, 2430.01,
       2425.55, 2428.37, 2452.51, 2444.04, 2438.97, 2443.05, 2444.24,
       2446.3 , 2457.59, 2471.65, 2476.55, 2457.85, 2465.54, 2465.1 ,
       2461.43, 2488.11, 2496.48, 2498.37, 2495.62, 2500.23, 2503.87,
       2506.65, 2508.24, 2500.6 , 2502.22, 2496.66, 2496.84, 2507.04,
       2510.06, 2519.36, 2529.12, 2534.58, 2537.74, 2552.07, 2549.33,
       2544.73, 2550.64, 2555.24, 2550.93, 2553.17, 2557.64, 2559.36,
       2561.26, 2562.1 , 2575.21, 2564.98, 2569.13, 2557.15, 2560.4 ,
       2581.07, 2572.83, 2575.26, 2579.36, 2579.85, 2587.84, 2591.13,
       2590.64, 2594.38, 2584.62, 2582.3 , 2584.84, 2578.87, 2564.62,
       2585.64, 2578.85, 2582.14, 2599.03, 2597.08, 2602.42, 2601.42,
       2627.04, 2626.07, 2647.58, 2642.22, 2639.44, 2629.57, 2629.27,
       2636.98, 2651.5 , 2659.99, 2664.11, 2662.85, 2652.01, 2675.81,
       2690.16, 2681.47, 2679.25, 2684.57, 2683.34, 2680.5 , 2682.62,
       2687.54, 2673.61, 2695.81, 2713.06, 2723.99, 2743.15, 2747.71,
       2751.29, 2748.23, 2767.56, 2786.24, 2776.42, 2802.56, 2798.03,
       2810.3 , 2832.97, 2839.13, 2837.54, 2839.25, 2872.87, 2853.53,
       2822.43, 2823.81, 2821.98, 2762.13, 2648.94, 2695.14, 2681.66,
       2581.  , 2619.55, 2656.  , 2662.94, 2698.63, 2731.2 , 2732.22,
       2716.26, 2701.33, 2703.96, 2747.3 , 2779.6 , 2744.28, 2713.83,
       2677.67, 2691.25, 2720.94, 2728.12, 2726.8 , 2738.97, 2786.57,
       2783.02, 2765.31, 2749.48, 2747.33, 2752.01, 2712.92, 2716.94,
       2711.93, 2643.69, 2588.26, 2658.55, 2612.62, 2605.  , 2640.87,
       2581.88, 2614.45, 2644.69, 2662.84, 2604.47, 2613.16, 2656.87,
       2642.19, 2663.99, 2656.3 , 2677.84, 2706.39, 2708.64, 2693.13,
       2670.14, 2670.29, 2634.56, 2639.4 , 2666.94, 2669.91, 2648.05,
       2654.8 , 2635.67, 2629.73, 2663.42, 2672.63, 2671.92, 2697.79,
       2723.07, 2727.72, 2730.13, 2711.45, 2722.46, 2720.13, 2712.97,
       2733.01, 2724.44, 2733.29, 2727.76, 2721.33, 2689.86, 2724.01,
       2705.27, 2734.62, 2746.87, 2748.8 , 2772.35, 2770.37, 2779.03,
       2782.  , 2786.85, 2775.63, 2782.49, 2779.66, 2773.75, 2762.59,
       2767.32, 2749.76, 2754.88, 2717.07, 2723.06, 2699.63, 2716.31,
       2718.37, 2726.71, 2713.22, 2736.61, 2759.82, 2784.17, 2793.84,
       2774.02, 2798.29, 2801.31, 2798.43, 2809.55, 2815.62, 2804.49,
       2801.83, 2806.98, 2820.4 , 2846.07, 2837.44, 2818.82, 2802.6 ,
       2816.29, 2813.36, 2827.22, 2840.35, 2850.4 , 2858.45, 2857.7 ,
       2853.58, 2833.28, 2821.93, 2839.96, 2818.37, 2840.69, 2850.13,
       2857.05, 2862.96, 2861.82, 2856.98, 2874.69, 2896.74, 2897.52,
       2914.04, 2901.13, 2901.52, 2896.72, 2888.6 , 2878.05, 2871.68,
       2877.13, 2887.89, 2888.92, 2904.18, 2904.98, 2888.8 , 2904.31,
       2907.95, 2930.75, 2929.67, 2919.37, 2915.56, 2905.97, 2914.  ,
       2913.98, 2924.59, 2923.43, 2925.51, 2901.61, 2885.57, 2884.43,
       2880.34, 2785.68, 2728.37, 2767.13, 2750.79, 2809.92, 2809.21,
       2768.78, 2767.78, 2755.88, 2740.69, 2656.1 , 2705.57, 2658.69,
       2641.25, 2682.63, 2711.74, 2740.37, 2738.31, 2755.45, 2813.89,
       2806.83, 2781.01, 2726.22, 2722.18, 2701.58, 2730.2 , 2736.27,
       2690.73, 2641.89, 2649.93, 2673.45, 2682.17, 2743.79, 2737.8 ,
       2760.17, 2790.37, 2700.06, 2695.95, 2633.08, 2637.72, 2636.78,
       2651.07, 2650.54, 2599.95, 2545.94, 2546.16, 2506.96, 2467.42,
       2416.62, 2467.7 , 2488.83, 2485.74, 2510.03, 2447.89, 2531.94,
       2549.69, 2574.41, 2584.96, 2596.64, 2596.26, 2582.61, 2610.3 ,
       2616.1 , 2635.96, 2670.71, 2632.9 , 2638.7 , 2642.33, 2664.76,
       2643.85, 2640.  , 2681.05, 2704.1 , 2706.53, 2724.87, 2737.7 ,
       2731.61, 2706.05, 2707.88, 2709.8 , 2744.73, 2753.03, 2745.73,
       2775.6 , 2779.76, 2784.7 , 2774.88, 2792.67, 2796.11, 2793.9 ,
       2792.38, 2784.49, 2803.69, 2792.81, 2789.65, 2771.45, 2748.93,
       2743.07, 2783.3 , 2791.52, 2810.92, 2808.48, 2822.48, 2832.94,
       2832.57, 2824.23, 2854.88, 2800.71, 2798.36, 2818.46, 2805.37,
       2815.44, 2834.4 , 2867.19, 2867.24, 2873.4 , 2879.39, 2892.74,
       2895.77, 2878.2 , 2888.21, 2888.32, 2907.41, 2905.58, 2907.06,
       2900.45, 2905.03, 2907.97, 2933.68, 2927.25, 2926.17, 2939.88,
       2943.03, 2945.83, 2923.73, 2917.52, 2945.64, 2932.47, 2884.05,
       2879.42, 2870.72, 2881.4 , 2811.87, 2834.41, 2850.96, 2876.32,
       2859.53, 2840.23, 2864.36, 2856.27, 2822.24, 2826.06, 2802.39,
       2788.86, 2752.06, 2744.45, 2803.27, 2826.15, 2843.49, 2873.34,
       2886.73, 2885.72, 2879.84, 2891.64, 2886.98, 2889.67, 2917.75,
       2926.46, 2954.18, 2950.46, 2945.35, 2917.38, 2913.78, 2924.92,
       2941.76, 2964.33, 2973.01, 2995.82, 2975.95, 2979.63, 2993.07,
       2999.91, 3013.77, 3014.3 , 3004.04, 2984.42, 2995.11, 2976.61,
       2985.03, 3005.47, 3019.56, 3003.67, 3025.86, 3020.97, 3013.18,
       2980.38, 2953.56, 2932.05, 2844.74, 2881.77, 2883.98, 2938.09,
       2918.65, 2882.7 , 2926.32, 2840.6 , 2847.6 , 2888.68, 2923.65,
       2900.51, 2924.43, 2922.95, 2847.11, 2878.38, 2869.16, 2887.94,
       2924.58, 2906.27, 2937.78, 2976.  , 2978.71, 2978.43, 2979.39,
       3000.93, 3009.57, 3007.39, 2997.96, 3005.7 , 3006.73, 3006.79,
       2992.07, 2991.78, 2966.6 , 2984.87, 2977.62, 2961.79, 2976.74,
       2940.25, 2887.61, 2910.63, 2952.01, 2938.79, 2893.06, 2919.4 ,
       2938.13, 2970.27, 2966.15, 2995.68, 2989.69, 2997.95, 2986.2 ,
       3006.72, 2995.99, 3004.52, 3010.29, 3022.55, 3039.42, 3036.89,
       3046.77, 3037.56, 3066.91, 3078.27, 3074.62, 3076.78, 3085.18,
       3093.08, 3091.84, 3094.04, 3096.63, 3120.46, 3122.03, 3120.18,
       3108.46, 3103.54, 3110.29, 3133.64, 3140.52, 3153.63, 3140.98,
       3113.87, 3093.2 , 3112.76, 3117.43, 3145.91, 3135.96, 3132.52,
       3141.63, 3168.57, 3168.8 , 3191.45, 3192.52, 3191.14, 3205.37,
       3221.22, 3224.01, 3223.38, 3239.91, 3240.02, 3221.29, 3230.78,
       3257.85, 3234.85, 3246.28, 3237.18, 3253.05, 3274.7 , 3265.35,
       3288.13, 3283.15, 3289.29, 3316.81, 3329.62, 3320.79, 3321.75,
       3325.54, 3295.47, 3243.63, 3276.24, 3273.4 , 3283.66, 3225.52,
       3248.92, 3297.59, 3334.69, 3345.78, 3327.71, 3352.09, 3357.75,
       3379.45, 3373.94, 3380.16, 3370.29, 3386.15, 3373.23, 3337.75,
       3225.89, 3128.21, 3116.39, 2978.76, 2954.22, 3090.23, 3003.37,
       3130.12, 3023.94, 2972.37, 2746.56, 2882.23, 2741.38, 2480.64,
       2711.02, 2386.13, 2529.19, 2398.1 , 2409.39, 2304.92, 2237.4 ,
       2447.33, 2475.56, 2630.07, 2541.47, 2626.65, 2584.59, 2470.5 ,
       2526.9 , 2488.65, 2663.68, 2659.41, 2749.98, 2789.82, 2761.63,
       2846.06, 2783.36, 2799.55, 2874.56, 2823.16, 2736.56, 2799.31,
       2797.8 , 2836.74, 2878.48, 2863.39, 2939.51])

In [16]:
df["Oil_WTI_price_USD"].unique()

array([ 95.14,  91.9 ,  92.15,  93.96,  97.23,  97.34,  97.24,  99.98,
       100.12, 100.27, 103.46, 102.2 , 102.88, 105.34, 101.82,  98.29,
       100.08,  99.97, 100.05, 101.25, 101.57, 100.29, 103.55, 103.7 ,
       104.35, 100.07,  99.81, 100.32, 100.89, 101.74, 104.31, 104.78,
       103.4 , 103.07, 103.17, 105.04, 106.95, 107.95, 106.83, 106.49,
       105.18, 104.06, 101.48, 101.73, 103.84, 103.81, 104.91,  97.86,
        98.26,  97.57,  94.35,  93.61,  95.39,  96.44,  95.5 ,  92.73,
        92.18,  92.86,  93.07,  93.6 ,  91.17,  89.76,  90.33,  85.76,
        81.82,  83.25,  81.27,  82.25,  77.15,  78.71,  77.43,  74.13,
        74.55,  74.04,  65.94,  68.98,  66.73,  60.99,  55.97,  56.91,
        55.25,  53.45,  47.98,  48.35,  46.06,  46.37,  47.85,  45.84,
        47.79,  49.25,  50.48,  48.8 ,  53.56,  49.95,  49.56,  47.65,
        51.53,  48.42,  44.88,  43.93,  44.02,  48.75,  50.12,  53.95,
        51.63,  51.95,  56.69,  56.17,  57.05,  59.1 ,  58.92,  58.99,
        60.5 ,  57.3 ,  58.88,  57.69,  59.67,  60.15,  59.96,  59.53,
        60.41,  60.01,  59.48,  52.48,  52.76,  51.4 ,  50.59,  47.17,
        48.53,  45.13,  43.11,  42.45,  41.93,  41.  ,  38.5 ,  45.38,
        46.02,  45.85,  47.12,  46.17,  45.55,  44.4 ,  44.75,  47.86,
        46.7 ,  47.3 ,  45.91,  44.9 ,  43.21,  46.6 ,  46.12,  45.27,
        42.95,  40.73,  39.39,  39.27,  39.93,  37.46,  35.65,  36.31,
        34.98,  36.76,  37.88,  36.81,  33.29,  30.42,  28.47,  32.07,
        30.31,  33.21,  32.29,  27.96,  29.32,  30.77,  30.35,  34.39,
        35.91,  37.9 ,  37.77,  38.43,  41.45,  36.91,  35.36,  34.3 ,
        37.3 ,  41.7 ,  40.88,  42.76,  41.67,  46.03,  43.77,  44.68,
        46.22,  47.72,  48.16,  49.1 ,  48.69,  49.71,  50.52,  47.92,
        48.95,  45.8 ,  48.27,  47.37,  46.82,  45.93,  45.23,  43.96,
        41.9 ,  39.5 ,  41.83,  43.06,  43.51,  46.81,  47.54,  47.64,
        46.97,  43.17,  45.47,  44.91,  43.04,  43.34,  46.1 ,  47.07,
        48.67,  49.76,  50.47,  51.59,  49.45,  48.72,  45.32,  44.96,
        43.39,  43.29,  45.37,  46.72,  45.29,  51.7 ,  51.72,  50.84,
        51.01,  52.22,  52.01,  53.8 ,  53.26,  50.82,  52.36,  51.39,
        52.14,  52.75,  53.81,  53.01,  52.99,  53.11,  54.02,  53.99,
        54.04,  52.63,  49.83,  47.24,  48.34,  47.  ,  47.02,  50.3 ,
        51.14,  53.38,  52.62,  50.26,  49.22,  46.23,  46.46,  47.81,
        49.04,  51.12,  49.58,  48.32,  46.41,  44.73,  44.24,  42.48,
        42.53,  42.86,  43.24,  44.25,  44.74,  45.11,  45.52,  45.06,
        45.48,  46.53,  46.4 ,  47.1 ,  46.73,  45.78,  46.21,  47.77,
        48.58,  49.05,  49.72,  50.21,  49.19,  49.6 ,  49.03,  49.57,
        49.37,  49.07,  49.59,  48.54,  48.81,  47.59,  47.57,  46.8 ,
        48.59,  47.39,  48.45,  45.96,  47.26,  47.32,  48.63,  49.13,
        47.44,  48.06,  48.21,  49.3 ,  49.86,  49.9 ,  49.88,  49.54,
        50.29,  50.58,  50.33,  51.85,  51.62,  51.67,  50.44,  50.  ,
        50.79,  49.34,  50.93,  51.3 ,  50.61,  51.43,  51.86,  51.87,
        52.05,  51.29,  51.91,  52.32,  51.97,  52.41,  53.92,  54.11,
        54.36,  54.32,  54.55,  55.63,  57.34,  57.19,  56.82,  57.16,
        56.75,  56.77,  55.67,  55.28,  55.14,  56.21,  56.84,  57.88,
        58.94,  58.1 ,  57.96,  57.25,  57.4 ,  58.35,  57.48,  57.66,
        55.79,  56.5 ,  57.15,  57.84,  57.12,  56.59,  57.  ,  57.29,
        57.17,  57.49,  58.09,  58.34,  58.25,  59.55,  59.84,  60.46,
        60.37,  61.61,  61.98,  61.49,  61.73,  62.92,  63.6 ,  63.81,
        64.22,  63.82,  63.92,  63.96,  63.38,  63.66,  64.45,  65.69,
        65.62,  66.27,  65.71,  64.64,  64.82,  65.92,  65.5 ,  64.18,
        63.48,  61.91,  61.3 ,  59.2 ,  59.41,  59.33,  60.7 ,  61.48,
        61.89,  62.72,  63.52,  62.94,  61.43,  60.98,  61.19,  62.49,
        62.54,  61.09,  60.13,  62.02,  61.35,  60.69,  60.89,  61.16,
        62.29,  62.01,  63.37,  65.1 ,  64.25,  65.8 ,  65.49,  65.21,
        64.3 ,  64.87,  63.05,  63.41,  63.35,  63.53,  62.03,  63.4 ,
        65.48,  66.81,  67.07,  67.35,  66.23,  66.5 ,  68.44,  68.3 ,
        68.26,  67.61,  67.66,  68.  ,  68.18,  68.11,  68.56,  67.28,
        67.91,  68.45,  69.71,  70.74,  68.83,  71.16,  71.36,  70.69,
        71.01,  71.34,  71.43,  71.47,  71.23,  72.26,  72.09,  71.85,
        70.77,  67.92,  66.8 ,  68.24,  66.98,  65.81,  64.76,  65.51,
        64.75,  65.96,  65.77,  66.1 ,  66.38,  66.63,  66.91,  65.01,
        65.91,  65.09,  65.68,  69.02,  69.91,  75.23,  77.41,  73.45,
        73.89,  74.19,  73.05,  73.78,  73.93,  74.11,  70.47,  70.28,
        71.03,  68.22,  68.03,  68.78,  69.42,  70.31,  67.9 ,  71.13,
        71.59,  68.66,  71.19,  69.88,  68.8 ,  68.95,  68.49,  69.01,
        69.17,  66.92,  67.25,  67.04,  65.07,  65.44,  65.93,  67.32,
        67.85,  69.13,  69.97,  68.54,  69.68,  70.25,  69.84,  69.82,
        68.69,  67.81,  67.73,  67.55,  69.29,  70.37,  68.6 ,  68.86,
        69.87,  71.08,  70.8 ,  73.23,  73.4 ,  72.22,  72.18,  73.16,
        75.37,  75.16,  76.4 ,  74.44,  74.26,  74.27,  74.95,  73.18,
        70.97,  71.41,  71.84,  71.93,  69.63,  68.63,  69.16,  69.25,
        66.49,  66.56,  67.58,  67.  ,  66.18,  65.31,  63.67,  63.12,
        62.16,  61.69,  60.71,  60.19,  59.85,  56.16,  56.45,  56.49,
        53.39,  54.41,  51.46,  51.31,  50.06,  50.78,  52.98,  53.21,
        51.54,  51.07,  51.65,  51.04,  52.69,  51.26,  49.8 ,  47.96,
        45.64,  46.04,  44.48,  45.15,  46.31,  46.92,  47.76,  52.19,
        52.42,  51.44,  50.31,  51.8 ,  52.08,  51.83,  53.6 ,  52.59,
        52.44,  52.94,  53.53,  51.79,  53.07,  54.18,  53.84,  55.29,
        54.57,  53.69,  53.94,  52.68,  52.43,  53.14,  54.4 ,  55.58,
        56.12,  56.9 ,  56.95,  57.01,  55.32,  55.4 ,  56.92,  57.21,
        55.76,  56.6 ,  56.55,  56.22,  55.77,  56.79,  56.89,  58.27,
        58.59,  58.51,  59.09,  59.12,  60.12,  59.98,  58.87,  58.71,
        59.87,  59.39,  59.29,  61.59,  62.53,  62.46,  62.12,  63.1 ,
        64.37,  64.05,  64.62,  63.61,  63.86,  63.43,  64.01,  63.74,
        64.02,  65.66,  66.24,  65.23,  63.29,  63.39,  63.83,  63.55,
        61.75,  62.3 ,  61.41,  62.13,  61.58,  61.65,  60.97,  61.82,
        62.93,  62.77,  63.02,  61.42,  57.65,  58.4 ,  58.91,  58.84,
        56.47,  53.49,  53.25,  53.5 ,  51.57,  53.33,  53.3 ,  51.13,
        52.38,  52.47,  51.94,  53.86,  53.74,  56.88,  57.35,  57.73,
        57.63,  59.17,  59.18,  58.2 ,  56.  ,  57.06,  57.57,  60.28,
        59.93,  59.99,  59.3 ,  57.44,  55.08,  55.42,  55.87,  56.58,
        55.9 ,  55.88,  56.04,  56.85,  58.04,  58.53,  53.64,  54.63,
        52.6 ,  54.98,  55.16,  54.51,  54.83,  56.24,  56.18,  55.65,
        55.33,  54.08,  53.54,  54.99,  56.67,  55.07,  53.91,  56.33,
        57.37,  55.66,  55.13,  54.76,  59.26,  58.19,  57.92,  58.69,
        57.22,  56.38,  55.95,  54.09,  52.67,  52.84,  52.64,  53.57,
        52.81,  53.42,  53.89,  53.75,  53.28,  54.21,  56.11,  56.52,
        55.6 ,  55.34,  54.85,  57.04,  56.15,  57.02,  56.57,  57.54,
        54.93,  56.71,  58.36,  57.68,  57.79,  58.12,  58.46,  58.42,
        59.22,  58.74,  60.11,  60.21,  60.88,  60.93,  60.43,  60.51,
        61.17,  61.72,  61.76,  61.66,  61.14,  63.  ,  63.27,  62.7 ,
        59.65,  59.56,  59.02,  58.17,  57.86,  58.52,  58.55,  56.76,
        55.51,  53.09,  53.29,  51.58,  50.87,  50.94,  50.34,  51.41,
        52.03,  52.1 ,  53.31,  53.77,  53.36,  51.36,  49.78,  44.83,
        46.78,  47.27,  45.9 ,  41.14,  31.05,  34.47,  33.13,  31.56,
        31.72,  28.96,  26.96,  20.48,  25.09,  19.48,  23.33,  21.03,
        20.75,  16.6 ,  15.48,  14.1 ,  20.51,  20.28,  25.18,  28.36,
        26.21,  23.54,  24.97,  22.9 ,  22.36,  20.15,  19.96,  19.82,
        18.31, -36.98,   8.91,  13.64,  15.06,  15.99,  12.17,  12.4 ,
        15.04])

In [17]:
df["M2_money_supply_USA"].unique()

array([11089.3, 11140.9, 11266.3, 11319.5, 11262.8, 11324.8, 11379.9,
       11411. , 11459. , 11526.8, 11602.8, 11747.9, 11746.9, 11835.1,
       11944.9, 11992.7, 11896.1, 11950.7, 12001.3, 12058.7, 12126.3,
       12159.8, 12286.2, 12416.1, 12467.2, 12506.1, 12673.9, 12767.5,
       12697.4, 12777.9, 12839.3, 12937. , 13007.7, 13072.4, 13185.5,
       13293.8, 13275.7, 13299.5, 13485.6, 13558.5, 13467.3, 13515.2,
       13577.3, 13646.1, 13696.5, 13741.6, 13810.9, 13936.6, 13856.2,
       13842.2, 14024. , 14068. , 13988.9, 14080.6, 14115.1, 14171.6,
       14207.2, 14209.7, 14263.2, 14456.5, 14433.6, 14411.4, 14582.9,
       14633.9, 14584.1, 14743.5, 14822.7, 14903.9, 14994.9, 15121. ,
       15266.6, 15418. , 15420.9, 15457.2, 16181. , 17269.8])

In [18]:
#To describe the dataframe
df.describe()

,BTC_price_USD,n_transactions,fee_USD,btc_search_trends,Gold_price_USD,SP500_close_index,Oil_WTI_price_USD,M2_money_supply_USA
count,1002.000000,1002.000000,1002.000000,1002.000000,1002.000000,1002.000000,1002.000000,1002.000000
mean,5352.851926,254421.630739,2.230409,15.163673,1369.540319,2584.999880,57.670948,13867.278842
std,3892.224190,88589.954049,5.568724,15.852566,114.562397,383.177031,15.852663,1274.266180
min,172.000000,54142.000000,0.030000,2.000000,1097.700000,1755.200000,-36.980000,11089.300000
25%,884.052500,207520.500000,0.230000,6.000000,1293.550000,2265.067500,49.545000,13293.800000
50%,5895.335000,267637.500000,0.700000,13.000000,1345.650000,2672.275000,56.285000,14024.000000
75%,8171.610000,322157.500000,1.767500,17.750000,1420.275000,2864.117500,63.950000,14584.100000
max,18911.790000,490644.000000,54.790000,100.000000,1768.900000,3386.150000,107.950000,17269.800000

In [19]:
#Checking datatype and information about dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1002 entries, 0 to 2309
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date                 1002 non-null   object
 1   BTC_price_USD        1002 non-null   float64
 2   n_transactions       1002 non-null   float64
 3   fee_USD              1002 non-null   float64
 4   btc_search_trends    1002 non-null   int64
 5   Gold_price_USD       1002 non-null   float64
 6   SP500_close_index    1002 non-null   float64
 7   Oil_WTI_price_USD    1002 non-null   float64
 8   M2_money_supply_USA  1002 non-null   float64
dtypes: float64(7), int64(1), object(1)
memory usage: 78.3+ KB

Checking duplicate values of dataframe

In [20]:
#Checking for duplicate data
df.duplicated()

0       False
6       False
12      False
15      False
21      False
        ...
2303    False
2304    False
2307    False
2308    False
2309    False
Length: 1002, dtype: bool

In [21]:
#find sum of duplicate data
sum(df.duplicated())

0

In [22]:
#Checking sum of missing values
df.isnull().sum()

Date                   0
BTC_price_USD          0
n_transactions         0
fee_USD                0
btc_search_trends      0
Gold_price_USD         0
SP500_close_index      0
Oil_WTI_price_USD      0
M2_money_supply_USA    0
dtype: int64

In [23]:
df.columns

Index(['Date', 'BTC_price_USD', 'n_transactions', 'fee_USD',
       'btc_search_trends', 'Gold_price_USD', 'SP500_close_index',
       'Oil_WTI_price_USD', 'M2_money_supply_USA'],
      dtype='object')

In [24]:
df['BTC_price_USD'].value_counts()

569.01     2
2600.00    2
376.03     2
4032.25    1
3246.64    1
          ..
4612.12    1
4613.84    1
4232.93    1
4198.59    1
7765.33    1
Name: BTC_price_USD, Length: 999, dtype: int64

In [25]:
print("Minimum BTC_price_USD value is:", df.BTC_price_USD.min())
print("Maximum BTC_price_USD value is:", df.BTC_price_USD.max())

Minimum BTC_price_USD value is: 172.0
Maximum BTC_price_USD value is: 18911.79

In [26]:
p.Categorical(df['btc_search_trends']).describe()

            counts     freqs
categories
2               36  0.035928
3              158  0.157685
4               27  0.026946
5                8  0.007984
6               26  0.025948
7                8  0.007984
8               27  0.026946
9                7  0.006986
10              84  0.083832
11              19  0.018962
12              82  0.081836
13             143  0.142715
14              55  0.054890
15              29  0.028942
16              20  0.019960
17              22  0.021956
18              42  0.041916
19              22  0.021956
20              43  0.042914
21              20  0.019960
22              43  0.042914
40              19  0.018962
44              21  0.020958
54              21  0.020958
100             20  0.019960

In [27]:
p.Categorical(df['BTC_price_USD']).describe()

            counts     freqs
categories
172.0            1  0.000998
210.71           1  0.000998
220.36           1  0.000998
222.13           1  0.000998
222.55           1  0.000998
...            ...       ...
16860.88         1  0.000998
16916.8          1  0.000998
17382.94         1  0.000998
18905.26         1  0.000998
18911.79         1  0.000998

[999 rows x 2 columns]

In [28]:
df.corr()

,BTC_price_USD,n_transactions,fee_USD,btc_search_trends,Gold_price_USD,SP500_close_index,Oil_WTI_price_USD,M2_money_supply_USA
BTC_price_USD,1.000000,0.596925,0.517846,0.677435,0.523268,0.792344,-0.004852,0.678480
n_transactions,0.596925,1.000000,0.273090,0.384363,0.376860,0.720957,-0.420285,0.771463
fee_USD,0.517846,0.273090,1.000000,0.834244,0.011837,0.116217,-0.000592,0.054859
btc_search_trends,0.677435,0.384363,0.834244,1.000000,0.142426,0.289335,-0.029324,0.237495
Gold_price_USD,0.523268,0.376860,0.011837,0.142426,1.000000,0.557169,-0.196017,0.676179
SP500_close_index,0.792344,0.720957,0.116217,0.289335,0.557169,1.000000,-0.104263,0.864312
Oil_WTI_price_USD,-0.004852,-0.420285,-0.000592,-0.029324,-0.196017,-0.104263,1.000000,-0.439634
M2_money_supply_USA,0.678480,0.771463,0.054859,0.237495,0.676179,0.864312,-0.439634,1.000000

Before Pre-Processing:

In [29]:
df.head()

,Date,BTC_price_USD,n_transactions,fee_USD,btc_search_trends,Gold_price_USD,SP500_close_index,Oil_WTI_price_USD,M2_money_supply_USA
0,2014-01-02,749.27,54770.0,0.18,8,1225.0,1831.98,95.14,11089.3
6,2014-01-08,790.00,61439.0,0.18,8,1225.3,1837.49,91.90,11089.3
12,2014-01-14,823.00,57378.0,0.22,8,1245.2,1838.88,92.15,11089.3
15,2014-01-17,817.15,59026.0,0.19,8,1251.7,1838.70,93.96,11089.3
21,2014-01-23,819.62,63576.0,0.19,8,1262.6,1828.46,97.23,11089.3

After Pre-Processing:

In [30]:
df.columns

Index(['Date', 'BTC_price_USD', 'n_transactions', 'fee_USD',
       'btc_search_trends', 'Gold_price_USD', 'SP500_close_index',
       'Oil_WTI_price_USD', 'M2_money_supply_USA'],
      dtype='object')

In [31]:
from sklearn.preprocessing import LabelEncoder
var_mod = ['Date', 'BTC_price_USD', 'n_transactions', 'fee_USD',
       'btc_search_trends', 'Gold_price_USD', 'SP500_close_index',
       'Oil_WTI_price_USD', 'M2_money_supply_USA']
le = LabelEncoder()
for i in var_mod:
    df[i] = le.fit_transform(df[i]).astype(str)

In [32]:
df.head(20)

,Date,BTC_price_USD,n_transactions,fee_USD,btc_search_trends,Gold_price_USD,SP500_close_index,Oil_WTI_price_USD,M2_money_supply_USA
0,0,233,1,15,6,45,7,839,0
6,1,240,10,15,6,46,8,829,0
12,2,246,2,19,6,68,10,830,0
15,3,244,5,16,6,78,9,837,0
21,4,245,14,16,6,110,4,843,0
27,5,239,7,14,6,109,1,845,0
33,6,243,35,13,7,78,0,844,1
36,7,236,42,11,7,112,2,852,1
39,8,224,23,10,7,137,3,856,1
42,9,216,28,11,7,231,6,857,1
48,10,202,40,10,7,311,5,872,1
54,11,160,65,8,7,398,12,867,1
57,12,174,41,8,7,314,17,868,1
60,13,163,67,11,4,432,13,884,3
63,14,220,43,10,4,439,28,866,3
69,15,206,57,10,4,500,22,849,3
75,16,201,0,8,4,463,26,855,3
78,17,179,49,12,4,371,20,851,3
81,18,161,44,9,4,269,16,853,3
84,19,171,45,6,4,216,14,861,3